[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mixsol"
authors = [{name = "Rishi E Kumar", email = "rishi42@gmail.com"}]
dynamic = ["version", "description"]
